### ISSUE TITLE
Add MobaXTerm and other "packages"?

### ISSUE THREAD

**Issue by TobiX** [RUB-NDS/Terrapin-Website#3]
Not sure if this clears the bar for "notable" SSH "clients" and if it should be listed on the website, but it seems to me that MobaXterm is a popular "remote shell package" for Windows. They ship updated versions of PuTTY and OpenSSH in version 23.6 (2023-12-30), see https://mobaxterm.mobatek.net/download-home-edition.html.

PS: Maybe list "products shipping SSH implementations" on a new page? I just realized this opens the floodgate for quite a lot of packages, but some of those wrote their own advisories (for example, [Gitea](https://blog.gitea.com/release-of-1.21.3) or [Forgejo](https://codeberg.org/forgejo/forgejo/src/branch/forgejo/RELEASE-NOTES.md#1-21-3-0))

**Comment by TrueSkrillor** [comment]
This is one of the issues we faced during responsible disclosure, as there are a lot of custom SSH clients building on top of OpenSSH or PuTTY, and it is hard to estimate their actual usage statistics. MobaXTerm is quite common (I believe), so it might be justified to be added to this list. Regarding the "products shipping SSH implementations," I'll think about how to integrate them into the existing website once I return from vacation by next week.

**Comment by TrueSkrillor** [comment]
MobaXterm has been added to the table, I'll keep this issue open until the issue regarding "products shipping SSH implementations" has been dealt with.

**Comment by TrueSkrillor** [comment]
I decided to simply add such products to the table as I already did this with FileZilla and WinSCP for example (on request only). Of course, I won't be including unrelated products that simply bumped their golang x/crypto dependency.
