### ISSUE TITLE
Jenkins' trilead-ssh2 missing?

### ISSUE THREAD

**Issue by TobiX** [RUB-NDS/Terrapin-Website#4]
When trilead-ssh2 was abandoned by its original developer, multiple forks were created:

- ConnectBot's sshlib: https://github.com/connectbot/sshlib (Terrapin fix: https://github.com/connectbot/sshlib/commit/5c8b534f6e97db7ac0e0e579331213aa25c173ab)
- Jenkins trilead-ssh2: https://github.com/jenkinsci/trilead-ssh2 (No Terrapin fix yet)
- maybe more?

At least ConnectBot's and Jenkins' version seem to be (more or less) actively maintained, so it probably would be a good idea to list both on the Terrapin website?!?

**Comment by TrueSkrillor** [comment]
I've added the Jenkins CI version of trilead-ssh2 to the list of affected products (it does support CBC-EtM, but not ChaCha20-Poly1305). I've also checked their issue tracker, it doesn't seem like there is an open ticket there so I guess I will be creating one within the next few days.

**Comment by kevinmehall** [comment]
"trilead-ssh2 (Jenkins CI)" is now listed on https://terrapin-attack.com/patches.html, however reading [their patch](https://github.com/jenkinsci/trilead-ssh2/commit/be42b6fefd823495a0a715f8e4ff52470a183b33) it just blocks the use of `chacha20-poly1305@openssh.com` kex (which I don't think it even supports) and `hmac-sha2-512-etm@openssh.com` and `hmac-sha2-256-etm@openssh.com` MACs, but does not implement `kex-strict-c-v00@openssh.com`.
